task :default => :new

require 'fileutils'

desc "创建新 post"
task :new do
    puts "请输入 post 标题："
    @name = STDIN.gets.chomp
    puts "请输入 post 子标题："
    @subtitle = STDIN.gets.chomp
    @date = Time.now.strftime("%F")
    @post_name = "#{@date}-#{@name}.markdown"
    if File.exist?(@post_name)
            abort("文件名已经存在！创建失败")
    end
    FileUtils.touch(@post_name)
    open(@post_name, 'a') do |file|
            file.puts "---"
            file.puts "layout: post"
            file.puts "title: #{@name}"
            file.puts "subtitle: #{@subtitle}"
            file.puts "author: ALin"
            file.puts "date: #{Time.now}"
            file.puts "---"
    end
    exec "open -a /Applications/Typora.app/ #{@post_name}"
end
